<a href="https://colab.research.google.com/github/kylama/musicrecognition/blob/main/MaSridharMusicCategorizationNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
# import libraries
import tensorflow as tf
import numpy as np
import pandas as pd
import statistics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [107]:
df = pd.read_csv('songs_normalize.csv')

xDf = df[['danceability', 'energy', 'key', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']]
yDf = df['genre']

In [108]:
y_relationship = np.reshape(yDf, (len(yDf), ))
for i, value in enumerate(yDf):
  x = value.split(", ")
  value = x[0]
  y_relationship[i] = value
print(y_relationship[0:15])

['pop' 'rock' 'pop' 'rock' 'pop' 'hip hop' 'hip hop' 'pop' 'pop'
 'Dance/Electronic' 'pop' 'pop' 'pop' 'rock' 'pop']


In [109]:
# transforming genre data (y) into numerical data
for i, element in enumerate(yDf):
  if element == 'pop':
    yDf[i] = 1
  elif element == 'hip hop':
    yDf[i] = 2
  elif element == 'rock':
    yDf[i] = 3
  elif element == 'country':
    yDf[i] = 4
  elif element == 'metal':
    yDf[i] = 5
  elif element == 'R&B':
    yDf[i] = 6
  elif element == 'Dance/Electronics':
    yDf[i] = 7
  elif element == 'Folk/Acoustic':
    yDf[i] = 8
  elif element == 'latin':
    yDf[i] = 9
  elif element == 'blues':
    yDf[i] = 10
  else:
    yDf[i] = 0
print(yDf)
print(yDf.shape)

Streaming output truncated to the last 5000 lines.
<ipython-input-109-53dd7c1f1f2f>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 1
<ipython-input-109-53dd7c1f1f2f>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 2
<ipython-input-109-53dd7c1f1f2f>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 1
<ipython-input-109-53dd7c1f1f2f>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice

0       1
1       3
2       1
3       3
4       1
       ..
1995    1
1996    1
1997    2
1998    1
1999    2
Name: genre, Length: 2000, dtype: object
(2000,)


In [110]:
x_train, x_test, y_train, y_test = train_test_split(xDf, yDf, test_size = 0.2 )
x_train.shape

(1600, 10)

In [111]:
# create a validation set
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)
x_val.shape


(320, 10)

In [112]:
x_train = x_train.to_numpy()
y_train = y_train.to_numpy()
y_val = y_val.to_numpy()
x_val = x_val.to_numpy()

In [131]:
# create MLP structure
model = Sequential()
model.add(Input(shape=(10,)))
model.add(Dense(250, activation='relu'))
model.add(Dense(1, activation='softmax'))

In [137]:
x_array = np.asarray(x_train).astype('float32')
x_val_array = np.asarray(x_val).astype('float32')
x_test_array = np.asarray(x_test).astype('float32')
y_array = np.asarray(y_train).astype('float32')
y_val_array = np.asarray(y_val).astype('float32')
y_test_array = np.asarray(y_test).astype('float32')
print(x_array.shape)
print(x_val_array.shape)
print(y_array.shape)
print(y_val_array.shape)

(1280, 10)
(320, 10)
(1280,)
(320,)


In [138]:
# compile and train model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_array, y_array, epochs=10, batch_size=32, validation_data=(x_val_array, y_val_array))

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (32, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/keras/src/losses/losses.py:27: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(32, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4863 - loss: 0.0000e+00 - val_accuracy: 0.4812 - val_loss: 0.0000e+00
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4856 - loss: 0.0000e+00 - val_accuracy: 0.4812 - val_loss: 0.0000e+00
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4720 - loss: 0.0000e+00 - val_accuracy: 0.4812 - val_loss: 0.0000e+00
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4826 - loss: 0.0000e+00 - val_accuracy: 0.4812 - val_loss: 0.0000e+00
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4740 - loss: 0.0000e+00 - val_accuracy: 0.4812 - val_loss: 0.0000e+00
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4761 - loss: 0.0000e+00 - val_accuracy: 0.4812 - val_loss: 0.0000e+00
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4735 - loss: 0.0000e+00 - val_accuracy: 0.4812 - val_loss: 0.0000e+00
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5054 - lo

In [141]:
# evaluate accuracy
y_pred = model.predict(x_test)
y_pred = tf.argmax(y_pred, axis=1)
# y_test = tf.argmax(y_test_oh, axis=1)
loss, acc = model.evaluate(x_test_array, y_test_array)
print("Test accuracy:", acc)
print("Confusion matrix:\n", confusion_matrix(y_test_array, y_pred))

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4524 - loss: 0.0000e+00 
Test accuracy: 0.4399999976158142
Confusion matrix:
 [[ 15   0   0   0   0   0   0   0   0]
 [176   0   0   0   0   0   0   0   0]
 [160   0   0   0   0   0   0   0   0]
 [ 35   0   0   0   0   0   0   0   0]
 [  5   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0]
 [  4   0   0   0   0   0   0   0   0]]
