<a href="https://colab.research.google.com/github/kylama/musicrecognition/blob/main/MaSridharMusicCatogarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import csv
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

# Import the k-Nearest Neighbors model from the sklearn library
from sklearn.neighbors import KNeighborsClassifier

# Import the train/test data split function from the sklearn library
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('songs_normalize.csv')

xDf = df[['danceability', 'energy', 'key', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']]
yDf = df['genre']

display(xDf)
display(yDf)

danceability  energy  key  loudness  speechiness  acousticness  \
0            0.751   0.834    1    -5.444       0.0437        0.3000   
1            0.434   0.897    0    -4.918       0.0488        0.0103   
2            0.529   0.496    7    -9.007       0.0290        0.1730   
3            0.551   0.913    0    -4.063       0.0466        0.0263   
4            0.614   0.928    8    -4.806       0.0516        0.0408   
...            ...     ...  ...       ...          ...           ...   
1995         0.842   0.734    1    -5.065       0.0588        0.0427   
1996         0.552   0.702    9    -5.707       0.1570        0.1170   
1997         0.847   0.678    9    -8.635       0.1090        0.0669   
1998         0.741   0.520    8    -7.513       0.0656        0.4500   
1999         0.695   0.762    0    -3.497       0.0395        0.1920   

      instrumentalness  liveness  valence    tempo  
0             0.000018    0.3550    0.894   95.053  
1             0.000000    0.6120    0.684  148.726  
2             0.000000    0.2510    0.278  136.859  
3             0.000013    0.3470    0.544  119.992  
4             0.001040    0.0845    0.879  172.656  
...                ...       ...      ...      ...  
1995          0.000000    0.1060    0.952  137.958  
1996          0.000021    0.1050    0.564  169.994  
1997          0.000000    0.2740    0.811   97.984  
1998          0.000002    0.2220    0.347  102.998  
1999          0.002440    0.0863    0.553  120.042  

[2000 rows x 10 columns]

0                    pop
1              rock, pop
2           pop, country
3            rock, metal
4                    pop
              ...       
1995                 pop
1996                 pop
1997    hip hop, country
1998                 pop
1999             hip hop
Name: genre, Length: 2000, dtype: object

In [ ]:
# split into training and testing set
# X_train, X_test, y_train, y_test = train_test_split(xDf, yDf, test_size=0.2) # test on 20% of the data, so train on 80% of the data

In [ ]:
y_relationship = np.reshape(yDf, (len(yDf), ))
for i, value in enumerate(yDf):
  x = value.split(", ")
  value = x[0]
  y_relationship[i] = value
print(y_relationship[0:15])

['pop' 'rock' 'pop' 'rock' 'pop' 'hip hop' 'hip hop' 'pop' 'pop'
 'Dance/Electronic' 'pop' 'pop' 'pop' 'rock' 'pop']


In [ ]:
# # specify model setup and train data
# model = KNeighborsClassifier(n_neighbors = 10, weights = 'distance')
# model.fit(X_train, y_train)
# scaler = StandardScaler() # standardize the data
# scaler.fit(X_train)
# X_train_scaled = scaler.transform(X_train)
# X_test_scaled = scaler.transform(X_test)

In [ ]:
# # transforming genre data (y) into numerical data
for i, element in enumerate(yDf):
  if element == 'pop':
    yDf[i] = 1
  elif element == 'hip hop':
    yDf[i] = 2
  elif element == 'rock':
    yDf[i] = 3
  elif element == 'country':
    yDf[i] = 4
  elif element == 'metal':
    yDf[i] = 5
  elif element == 'R&B':
    yDf[i] = 6
  elif element == 'Dance/Electronics':
    yDf[i] = 7
  elif element == 'Folk/Acoustic':
    yDf[i] = 8
  elif element == 'latin':
    yDf[i] = 9
  elif element == 'blues':
    yDf[i] = 10
  else:
    yDf[i] = 0
print(yDf)
print(yDf.shape)


Streaming output truncated to the last 5000 lines.
<ipython-input-109-843607efdbef>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 2
<ipython-input-109-843607efdbef>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 1
<ipython-input-109-843607efdbef>:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 0
<ipython-input-109-843607efdbef>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slic

0       1
1       3
2       1
3       3
4       1
       ..
1995    1
1996    1
1997    2
1998    1
1999    2
Name: genre, Length: 2000, dtype: object
(2000,)


<ipython-input-109-843607efdbef>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 2
<ipython-input-109-843607efdbef>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 2
<ipython-input-109-843607efdbef>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yDf[i] = 2
<ipython-input-109-843607efdbef>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documenta

In [ ]:
yDf

0       1
1       3
2       1
3       3
4       1
       ..
1995    1
1996    1
1997    2
1998    1
1999    2
Name: genre, Length: 2000, dtype: object

In [ ]:
copy = pd.DataFrame(yDf)
copy['genre'].unique()

array([1, 3, 2, 0, 5, 6, 8, 9, 4], dtype=object)

In [ ]:
copy

genre
0        1
1        3
2        1
3        3
4        1
...    ...
1995     1
1996     1
1997     2
1998     1
1999     2

[2000 rows x 1 columns]

In [ ]:
def KNN(k):
  accuracy = [] # declare an empty list to hold the accuracy
  for i in range(1): # for 10 times
    X_train, X_test, y_train, y_test = train_test_split(xDf, yDf, test_size = 0.2, random_state = i) # split the data into train/test split(remember to use a different random seet in each iteration, for this case 0 - 9)
    y_train = np.array(y_train.astype(int))
    y_test = np.array(y_test.astype(int))

    # y_relationship = np.reshape(y_train, (len(y_train), ))
    # for i, value in enumerate(y_relationship):
    #   x = value.split(", ")
    #   value = x[0]
    #   y_relationship[i] = value

    # transforming genre data (y) into numerical data
    # for i, element in enumerate(y_relationship):
    #   if element == 'pop':
    #     y_relationship[i] = 1
    #   elif element == 'hip hop':
    #     y_relationship[i] = 2
    #   elif element == 'rock':
    #     y_relationship[i] = 3
    #   elif element == 'country':
    #     y_relationship[i] = 4
    #   elif element == 'metal':
    #     y_relationship[i] = 5
    #   elif element == 'R&B':
    #     y_relationship[i] = 6
    #   elif element == 'Dance/Electronics':
    #     y_relationship[i] = 7
    #   elif element == 'Folk/Acoustic':
    #     y_relationship[i] = 8
    #   elif element == 'latin':
    #     y_relationship[i] = 9
    #   elif element == 'blues':
    #     y_relationship[i] = 10
    #   else:
    #     y_relationship[i] = 0

    scaler = StandardScaler() # standardize the data
    scaler.fit(X_train)
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    model = KNeighborsClassifier(n_neighbors = k, weights = "distance") # train a KNN model using the training data and labels
    model.fit(X_train_scaled, y_train)
    print(X_train_scaled)
    print(y_relationship)

    y_hat = model.predict(X_test_scaled)

    score = model.score(X_test_scaled, y_test) # calculate the accuracy of the model using the testing data

    accuracy.append(score) # append the accuracy to the list containing all accuracies;

  print(accuracy)

  avg_accuracy = sum(accuracy) / len(accuracy) # calculate the average accuracy by averaging all elements in the list holding all accuracies
  print("average accurcy of k =", k, ":", avg_accuracy)

In [ ]:
KNN(10)

[[-1.36873076  0.93092666 -1.22940199 ... -0.49460835 -0.27534948
  -1.04150617]
 [ 0.96168177 -2.5052336   0.42473384 ... -0.72381416  1.34450304
   1.72229586]
 [-0.53438553  0.18050086  0.97611245 ...  0.83015917  0.64317025
   2.24356642]
 ...
 [-0.32579922  0.08176062  0.97611245 ... -0.25629038 -0.82284153
  -0.44961499]
 [ 1.2206165  -0.83981493 -0.40233408 ... -0.6649356  -0.20295383
  -1.11492771]
 [-0.08844239 -0.64233445 -0.67802338 ...  0.67595343  0.82868408
   0.15646753]]
[1 3 1 ... 2 1 2]
[0.605]
average accurcy of k = 10 : 0.605


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(xDf, yDf, test_size = 0.2, random_state = i)
X_trainscaler = StandardScaler() # standardize the data
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled

array([[-1.18611353, -0.81716851, -1.22228678, ..., -0.52888529,
        -2.13127185,  0.94278471],
       [ 0.15901248, -2.01936216,  1.01755156, ..., -0.71398965,
        -0.45171537, -1.65323431],
       [-0.0250574 , -1.35363127, -0.10236761, ..., -0.9646368 ,
         0.58437466, -1.23540201],
       ...,
       [ 0.10237559, -0.89472939,  1.29753135, ..., -0.32721517,
        -0.93795061,  0.91241356],
       [ 2.10590539, -2.39423975, -0.10236761, ..., -0.52168279,
         0.06632964, -0.00645114],
       [ 0.48467457,  0.85039042, -1.22228678, ...,  0.95483059,
         1.43415026, -0.10342634]])

In [ ]:
y_train

1037    1
488     2
487     2
438     2
265     1
       ..
1643    3
1132    1
1984    2
1856    2
259     1
Name: genre, Length: 1600, dtype: object

In [ ]:
model.fit(X_train_scaled, y_train)

ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(xDf, yDf, test_size = 0.2, random_state = i)
scaler = StandardScaler() # standardize the data
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = KNeighborsClassifier(n_neighbors = 10, weights = "distance") # train a KNN model using the training data and labels
model.fit(X_train_scaled, y_train)

y_hat = model.predict(X_test_scaled)

score = model.score(X_test_scaled, y_test) # calculate the accuracy of the model using the testing data

print(score)


ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
new_df = pd.DataFrame(X_train_scaled)
new_df.describe()

0             1             2             3             4  \
count  1.600000e+03  1.600000e+03  1.600000e+03  1.600000e+03  1.600000e+03   
mean  -3.086420e-16 -7.105427e-17  1.010303e-16 -5.817569e-16  1.121325e-16   
std    1.000313e+00  1.000313e+00  1.000313e+00  1.000313e+00  1.000313e+00   
min   -3.798490e+00 -4.275737e+00 -1.502267e+00 -7.648448e+00 -8.330403e-01   
25%   -6.144350e-01 -6.410407e-01 -9.423070e-01 -4.936689e-01 -6.672848e-01   
50%    6.697754e-02  1.103304e-01  1.776122e-01  1.276302e-01 -4.608531e-01   
75%    6.775940e-01  7.792929e-01  7.375718e-01  6.942366e-01  2.758946e-01   
max    2.190861e+00  1.755267e+00  1.577511e+00  2.696144e+00  4.788410e+00   

                  5             6             7             8             9  
count  1.600000e+03  1.600000e+03  1.600000e+03  1.600000e+03  1.600000e+03  
mean   8.992806e-17  9.992007e-18 -2.053913e-16  2.264855e-16 -2.886580e-17  
std    1.000313e+00  1.000313e+00  1.000313e+00  1.000313e+00  1.000313e+00  
min   -7.363348e-01 -1.781878e-01 -1.144699e+00 -2.314405e+00 -2.202333e+00  
25%   -6.621295e-01 -1.781878e-01 -6.651927e-01 -7.300510e-01 -8.079070e-01  
50%   -4.259337e-01 -1.781878e-01 -4.136452e-01  2.997561e-02 -3.355412e-03  
75%    2.732060e-01 -1.773823e-01  4.434528e-01  8.036349e-01  5.481796e-01  
max    4.768682e+00  1.015328e+01  4.844183e+00  1.934018e+00  3.323531e+00

In [ ]:
new_df.isna().sum().sum()

0

In [ ]:
model.fit(X_train_scaled, np.array(y_train.astype(int)))

KNeighborsClassifier(n_neighbors=10, weights='distance')

In [ ]:
np.array(y_train.astype(int))

array([1, 2, 2, ..., 2, 2, 1])